[package]
name = "hello_world_zmq"
version = "0.1.0"
authors = ["KJ Dorow <kevin.e.dorow@email.wsu.edu>"]

[dependencies]
zmq = {git = "https://github.com/erickt/rust-zmq"}
snap = "~0.2"
protobuf = "~1"