[package]
name = "majordomo protob"
version = "0.1.0"
authors = ["KJ Dorow <kevin.e.dorow@email.wsu.edu>"]

[dependencies]
zmq = "*"
protoc-rust = "*"
protobuf = "*"
serde = "0.8"
serde_derive = "0.8"
snap = "*"

[[bin]]
name = "worker"
path = "src/worker.rs"
